### ISSUE TITLE
Nix expression for `sel4-kernel-oader` fails due to hash missmatch

### ISSUE THREAD

**Issue by wucke13** [seL4/rust-sel4#233]
```sh
nix-build  --attr worlds.default.sel4-kernel-loader
```

yields

```console
fetching git input 'git+https://github.com/coliasgroup/seL4.git'
fetching git input 'git+https://github.com/coliasgroup/dafny.git'
fetching git input 'git+https://github.com/coliasgroup/ring.git'
fetching git input 'git+https://github.com/coliasgroup/rust-embedded-fat.git'
fetching git input 'git+https://github.com/coliasgroup/verus.git'
fetching git input 'git+https://github.com/coliasgroup/volatile.git'
these 6 derivations will be built:
  /nix/store/gvwnmjs7r78asy776gcv0p0klfc21j6f-source.drv
  /nix/store/6imwh6cyx11w6044l5ninn6wrsh766ky-compiler-rt.drv
  /nix/store/vmi1p3vbaf7hl72l3nyakqbzafv1xl44-sysroot-aarch64-none-elf.drv
  /nix/store/8zrrfca9blx56pb7ch10b57c9x9fg5y8-config.drv
  /nix/store/34rs6c99ngca3y2cxdq8iqkrj84fl6y5-sel4-kernel-loader-intermediate-aarch64-none-elf.drv
  /nix/store/gplgmss0s0lnphq7c4vxbm828d3dkbjm-sel4-kernel-loader-aarch64-none-elf.drv
building '/nix/store/gvwnmjs7r78asy776gcv0p0klfc21j6f-source.drv'...

trying https://github.com/rust-lang/llvm-project/archive/rustc/19.1-2024-07-30.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  207M    0  207M    0     0  5418k      0 --:--:--  0:00:39 --:--:-- 7225k
unpacking source archive /build/19.1-2024-07-30.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/gvwnmjs7r78asy776gcv0p0klfc21j6f-source.drv':
        likely URL: https://github.com/rust-lang/llvm-project/archive/rustc/19.1-2024-07-30.tar.gz
         specified: sha256-fV51iDAbkRmWJj0twTmQKdZdLueMAKSZR6bBtgVPCbk=
            got:    sha256-lO1OCNs2nzp1Bo/JA+Enoo6cOepfRAHeKsyoeowzhzI=
error: 1 dependencies of derivation '/nix/store/6imwh6cyx11w6044l5ninn6wrsh766ky-compiler-rt.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vmi1p3vbaf7hl72l3nyakqbzafv1xl44-sysroot-aarch64-none-elf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8zrrfca9blx56pb7ch10b57c9x9fg5y8-config.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gplgmss0s0lnphq7c4vxbm828d3dkbjm-sel4-kernel-loader-aarch64-none-elf.drv' failed to build
```

**Comment by nspin** [comment]
Thanks for finding this.

A Nix expression fetching https://github.com/rust-lang/llvm-project was using the ref `rustc/19.1-2024-07-30`, which is a branch rather than a tag.

Fixed by https://github.com/seL4/rust-sel4/pull/234.

**Comment by wucke13** [comment]
Still fails for me (running on d6d2b48fc26a88221e0d5cede98ec6ecf13f4522 which already includes the PR you linked above):

`nix-build  --attr worlds.default.sel4-kernel-loader`, in particular `/nix/store/k5g59zxvab2k6gwpyfi65g2apb6w9nr7-seL4-aarch64-none-elf.drv`

<details>
<summary>Build Log</summary>

```console

this derivation will be built:
  /nix/store/k5g59zxvab2k6gwpyfi65g2apb6w9nr7-seL4-aarch64-none-elf.drv
building '/nix/store/k5g59zxvab2k6gwpyfi65g2apb6w9nr7-seL4-aarch64-none-elf.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/npxpsg7dh2ibc6ilvnpka9rcvwlgngc2-source
source root is source
Running phase: patchPhase
patching script interpreter paths in .
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
loading initial cache file /nix/store/wvrbi9z2pqhbg6pbplkdjyak67jy2hgn-settings.cmake
-- Extracting device tree from QEMU
-- qemu-system-aarch64: info: dtb dumped to /build/source/build/qemu-arm-virt.dtb. Exiting.
-- The C compiler identification is GNU 13.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /nix/store/wzf5ih7zl02s018m79xjkqbz74axi34n-aarch64-none-elf-gcc-wrapper-13.3.0/bin/aarch64-none-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/wzf5ih7zl02s018m79xjkqbz74axi34n-aarch64-none-elf-gcc-wrapper-13.3.0/bin/aarch64-none-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- /build/source/build/gen_headers/plat/machine/devices_gen.h is out of date. Regenerating from DTB...
-- Configuring done (1.2s)
-- Generating done (0.0s)
-- Build files have been written to: /build/source/build
Running phase: buildPhase
ninja: Entering directory `/build/source/build'
[1/42] Concatenating C filesr preprocessorion/sel4_invocation.h
FAILED: kernel_all.c /build/source/build/kernel_all.c
cd /build/source/build && /build/source/tools/cpp_gen.sh /build/source/src/api/faults.c /build/source/src/api/syscall.c /build/source/src/arch/arm/64/c_traps.c /build/source/src/arch/arm/64/idle.c /build/source/src/arch/arm/64/kernel/thread.c /build/source/src/arch/arm/64/kernel/vspace.c /build/source/src/arch/arm/64/machine/capdl.c /build/source/src/arch/arm/64/machine/fpu.c /build/source/src/arch/arm/64/machine/registerset.c /build/source/src/arch/arm/64/model/statedata.c /build/source/src/arch/arm/64/object/objecttype.c /build/source/src/arch/arm/api/faults.c /build/source/src/arch/arm/armv/armv8-a/64/cache.c /build/source/src/arch/arm/armv/armv8-a/64/user_access.c /build/source/src/arch/arm/benchmark/benchmark.c /build/source/src/arch/arm/c_traps.c /build/source/src/arch/arm/kernel/boot.c /build/source/src/arch/arm/kernel/thread.c /build/source/src/arch/arm/machine/cache.c /build/source/src/arch/arm/machine/debug.c /build/source/src/arch/arm/machine/errata.c /build/source/src/arch/arm/machine/gic_v2.c /build/source/src/arch/arm/machine/hardware.c /build/source/src/arch/arm/machine/io.c /build/source/src/arch/arm/machine/l2c_nop.c /build/source/src/arch/arm/object/interrupt.c /build/source/src/arch/arm/object/iospace.c /build/source/src/arch/arm/object/smc.c /build/source/src/arch/arm/object/smmu.c /build/source/src/arch/arm/object/tcb.c /build/source/src/arch/arm/object/vcpu.c /build/source/src/arch/arm/smp/ipi.c /build/source/src/assert.c /build/source/src/benchmark/benchmark.c /build/source/src/benchmark/benchmark_track.c /build/source/src/benchmark/benchmark_utilisation.c /build/source/src/drivers/serial/pl011.c /build/source/src/drivers/timer/generic_timer.c /build/source/src/fastpath/fastpath.c /build/source/src/inlines.c /build/source/src/kernel/boot.c /build/source/src/kernel/cspace.c /build/source/src/kernel/faulthandler.c /build/source/src/kernel/stack.c /build/source/src/kernel/thread.c /build/source/src/machine/capdl.c /build/source/src/machine/fpu.c /build/source/src/machine/io.c /build/source/src/machine/registerset.c /build/source/src/model/preemption.c /build/source/src/model/smp.c /build/source/src/model/statedata.c /build/source/src/object/cnode.c /build/source/src/object/endpoint.c /build/source/src/object/interrupt.c /build/source/src/object/notification.c /build/source/src/object/objecttype.c /build/source/src/object/tcb.c /build/source/src/object/untyped.c /build/source/src/smp/ipi.c /build/source/src/smp/lock.c /build/source/src/string.c /build/source/src/util.c /build/source/src/config/default_domain.c > kernel_all.c
/bin/sh: /build/source/tools/cpp_gen.sh: not found
[2/42] Generate syscall invocations
FAILED: gen_headers/arch/api/syscall.h /build/source/build/gen_headers/arch/api/syscall.h
cd /build/source/build && /build/source/tools/xmllint.sh --noout --schema /build/source/libsel4/include/api/syscall.xsd /build/source/libsel4/include/api/syscall.xml && /nix/store/hx89vlv61l4vm0dvn0zww817nckzh7ls-cmake-3.29.6/bin/cmake -E remove -f gen_headers/arch/api/syscall.h && python3 /build/source/tools/syscall_header_gen.py --xml /build/source/libsel4/include/api/syscall.xml --kernel_header gen_headers/arch/api/syscall.h
/bin/sh: /build/source/tools/xmllint.sh: not found
[8/42] Generate invocation header gen_headers/api/invocation.hation.h
ninja: build stopped: subcommand failed.
error: builder for '/nix/store/k5g59zxvab2k6gwpyfi65g2apb6w9nr7-seL4-aarch64-none-elf.drv' failed with exit code 1;
       last 35 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/npxpsg7dh2ibc6ilvnpka9rcvwlgngc2-source
       > source root is source
       > Running phase: patchPhase
       > patching script interpreter paths in .
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > loading initial cache file /nix/store/wvrbi9z2pqhbg6pbplkdjyak67jy2hgn-settings.cmake
       > -- Extracting device tree from QEMU
       > -- qemu-system-aarch64: info: dtb dumped to /build/source/build/qemu-arm-virt.dtb. Exiting.
       > -- The C compiler identification is GNU 13.3.0
       > -- The ASM compiler identification is GNU
       > -- Found assembler: /nix/store/wzf5ih7zl02s018m79xjkqbz74axi34n-aarch64-none-elf-gcc-wrapper-13.3.0/bin/aarch64-none-elf-gcc
       > -- Detecting C compiler ABI info
       > -- Detecting C compiler ABI info - done
       > -- Check for working C compiler: /nix/store/wzf5ih7zl02s018m79xjkqbz74axi34n-aarch64-none-elf-gcc-wrapper-13.3.0/bin/aarch64-none-elf-gcc - skipped
       > -- Detecting C compile features
       > -- Detecting C compile features - done
       > -- /build/source/build/gen_headers/plat/machine/devices_gen.h is out of date. Regenerating from DTB...
       > -- Configuring done (1.2s)
       > -- Generating done (0.0s)
       > -- Build files have been written to: /build/source/build
       > Running phase: buildPhase
       > ninja: Entering directory `/build/source/build'
       > [1/42] Concatenating C filesr preprocessorion/sel4_invocation.h
       > FAILED: kernel_all.c /build/source/build/kernel_all.c
       > cd /build/source/build && /build/source/tools/cpp_gen.sh /build/source/src/api/faults.c /build/source/src/api/syscall.c /build/source/src/arch/arm/64/c_traps.c /build/source/src/arch/arm/64/idle.c /build/source/src/arch/arm/64/kernel/thread.c /build/source/src/arch/arm/64/kernel/vspace.c /build/source/src/arch/arm/64/machine/capdl.c /build/source/src/arch/arm/64/machine/fpu.c /build/source/src/arch/arm/64/machine/registerset.c /build/source/src/arch/arm/64/model/statedata.c /build/source/src/arch/arm/64/object/objecttype.c /build/source/src/arch/arm/api/faults.c /build/source/src/arch/arm/armv/armv8-a/64/cache.c /build/source/src/arch/arm/armv/armv8-a/64/user_access.c /build/source/src/arch/arm/benchmark/benchmark.c /build/source/src/arch/arm/c_traps.c /build/source/src/arch/arm/kernel/boot.c /build/source/src/arch/arm/kernel/thread.c /build/source/src/arch/arm/machine/cache.c /build/source/src/arch/arm/machine/debug.c /build/source/src/arch/arm/machine/errata.c /build/source/src/arch/arm/machine/gic_v2.c /build/source/src/arch/arm/machine/hardware.c /build/source/src/arch/arm/machine/io.c /build/source/src/arch/arm/machine/l2c_nop.c /build/source/src/arch/arm/object/interrupt.c /build/source/src/arch/arm/object/iospace.c /build/source/src/arch/arm/object/smc.c /build/source/src/arch/arm/object/smmu.c /build/source/src/arch/arm/object/tcb.c /build/source/src/arch/arm/object/vcpu.c /build/source/src/arch/arm/smp/ipi.c /build/source/src/assert.c /build/source/src/benchmark/benchmark.c /build/source/src/benchmark/benchmark_track.c /build/source/src/benchmark/benchmark_utilisation.c /build/source/src/drivers/serial/pl011.c /build/source/src/drivers/timer/generic_timer.c /build/source/src/fastpath/fastpath.c /build/source/src/inlines.c /build/source/src/kernel/boot.c /build/source/src/kernel/cspace.c /build/source/src/kernel/faulthandler.c /build/source/src/kernel/stack.c /build/source/src/kernel/thread.c /build/source/src/machine/capdl.c /build/source/src/machine/fpu.c /build/source/src/machine/io.c /build/source/src/machine/registerset.c /build/source/src/model/preemption.c /build/source/src/model/smp.c /build/source/src/model/statedata.c /build/source/src/object/cnode.c /build/source/src/object/endpoint.c /build/source/src/object/interrupt.c /build/source/src/object/notification.c /build/source/src/object/objecttype.c /build/source/src/object/tcb.c /build/source/src/object/untyped.c /build/source/src/smp/ipi.c /build/source/src/smp/lock.c /build/source/src/string.c /build/source/src/util.c /build/source/src/config/default_domain.c > kernel_all.c
       > /bin/sh: /build/source/tools/cpp_gen.sh: not found
       > [2/42] Generate syscall invocations
       > FAILED: gen_headers/arch/api/syscall.h /build/source/build/gen_headers/arch/api/syscall.h
       > cd /build/source/build && /build/source/tools/xmllint.sh --noout --schema /build/source/libsel4/include/api/syscall.xsd /build/source/libsel4/include/api/syscall.xml && /nix/store/hx89vlv61l4vm0dvn0zww817nckzh7ls-cmake-3.29.6/bin/cmake -E remove -f gen_headers/arch/api/syscall.h && python3 /build/source/tools/syscall_header_gen.py --xml /build/source/libsel4/include/api/syscall.xml --kernel_header gen_headers/arch/api/syscall.h
       > /bin/sh: /build/source/tools/xmllint.sh: not found
       > [8/42] Generate invocation header gen_headers/api/invocation.hation.h
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/k5g59zxvab2k6gwpyfi65g2apb6w9nr7-seL4-aarch64-none-elf.drv'.
```

</details>

**Comment by nspin** [comment]
In my development environment, both native (NixOS 24.05 with  Nix version 2.18.5) and inside the Docker container at `./hacking/docker` (even without `https://coliasgroup.cachix.org` as a substituter), I get:

```
$ nix-instantiate -A worlds.default.seL4
/nix/store/s4bn1jjqjq8akq0p9fdgjyk3dgl9zn58-seL4-aarch64-none-elf.drv
```

Can you share some details about your environment so that we can find the cause of this Nix eval disparity?

**Comment by nspin** [comment]
When I run `nix-build -A worlds.default.seL4 --check`, I see:

```
patching script interpreter paths in .
./tools/xmllint.sh: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/vpvy79k1qq02p1vyqjk6nb89gwhxqvyb-bash-5.2p32/bin/bash"
...
```

Your build log had
```
patching script interpreter paths in .
```

but none of the `interpreter directive changed` lines. For some reason, in your build, `patchShebangs` isn't doing its job.

**Comment by wucke13** [comment]
I ran `nix-build --attr worlds.default.sel4-kernel-loader` on 5826be1a6c83803faeaa79cd9f164c26a5a32e7c on a different machine, and it succeeded. Checking out 5826be1a6c83803faeaa79cd9f164c26a5a32e7c on that other machine, it succeeds as well (no rebuild, the drv seems unchanged). Of my head, the only difference to the machine used earlier was that one was using Lix, instead of Nix. But I'm unaware of any incompatibility between Lix and Nix except for integer overflow behavior, which should not have any real-world impacts.
